apiVersion: monitoring.coreos.com/v1beta1
kind: AlertmanagerConfig
metadata:
  name: alertmanager-config
  namespace: monitoring
spec:
  route:
    receiver: "email"
    groupWait: 10s
    groupInterval: 10s
    repeatInterval: 1h
  receivers:
    - name: "email"
      emailConfigs:
        - to: "yaakovsm@gmail.com"
          from: "yaakovsm@gmail.com"
          smarthost: "smtp.gmail.com:587"
          authUsername: "yaakovsm@gmail.com"
          authIdentity: "yaakovsm@gmail.com"
          authPassword:
            name: gmail-auth
            key: password
  global:
    resolveTimeout: 5m